#!/bin/bash
# ==============================================================================
# Git Hook Installer for Pre-Execution Security Gate
# ==============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
GIT_HOOK_DIR="$PROJECT_ROOT/.git/hooks"
PRE_COMMIT_HOOK="$GIT_HOOK_DIR/pre-commit"

echo "=== Installing Security Gate Pre-Commit Hook ==="

if [ ! -d "$GIT_HOOK_DIR" ]; then
    echo "Error: .git/hooks directory not found at $GIT_HOOK_DIR"
    exit 1
fi

cat << 'EOF' > "$PRE_COMMIT_HOOK"
#!/bin/bash
# Pre-commit hook generated by install_hooks.sh
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../scripts" && pwd)"
GATE_SCRIPT="$SCRIPT_DIR/pre_apply_gate.sh"

echo "Running Pre-Execution Security Gate before git commit..."
if [ -x "$GATE_SCRIPT" ]; then
    "$GATE_SCRIPT"
else
    bash "$GATE_SCRIPT"
fi
EOF

chmod +x "$PRE_COMMIT_HOOK"
echo "✓ Pre-commit hook installed successfully at $PRE_COMMIT_HOOK"
